### ISSUE TITLE
Can't run Picam.Camera.start_link()

### ISSUE THREAD

**Issue by TheHardestBunnyAlive** [electricshaman/picam#33] opened 2018-08-08 00:02 UTC
I've installed a fresh version of Raspbian as well as Elixir and Nerves. I also downloaded this file and moved it into /home/pi. When I SSH into the file picam/lib/picam, I open up iex and type c("camera.ex"). Once I do this, it says
[Picam.Camera]
which I assume is correct. However when I go to run Picam.Camera.start_link() I get the following error.
![image](https://user-images.githubusercontent.com/4650048/43808807-b900b314-9a7c-11e8-84f6-e647b779d901.png)

Any help is much appreciated.

**Comment by pdgonzalez872** [comment] 2019-01-30 20:02
@TheHardestBunnyAlive Hi! So you are not using this in a Nerves application? Is this still an issue or can we close this out?

**Comment by TheHardestBunnyAlive** [comment] 2019-01-30 20:20
I ended up not using picam because I couldn't figure out the issue. You can
close it.

**Comment by GregMefford** [comment] 2019-02-10 14:46
It looks like the issue is that `elixir_make` would normally have compiled a C-based application that Elixir is trying to call. When you manually compile the Elixir code like this, the binary application isn't available where it should be. `mix compile` before running `IEx` should solve this in case someone else happens upon this issue in the future.

**Closed by GregMefford** 2019-02-10 14:46 UTC
